# Generated by Django 6.0.7 on 2026-07-23 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opshub', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrateur',
            options={'verbose_name': 'Administrateur', 'verbose_name_plural': 'Administrateurs'},
        ),
        migrations.AlterModelOptions(
            name='membretechcommand',
            options={'verbose_name': 'Membre Techcommand', 'verbose_name_plural': 'Membres Techcommand'},
        ),
        migrations.AlterModelOptions(
            name='teamlead',
            options={'verbose_name': 'Team-lead', 'verbose_name_plural': 'Team-leads'},
        ),
        migrations.RemoveField(
            model_name='motsclesassignation',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='outilmonitoring',
            name='documente_par',
        ),
    ]
