# Generated by Django 6.0.7 on 2026-07-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opshub', '0002_alter_administrateur_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='outil_team',
        ),
        migrations.AddField(
            model_name='service',
            name='outils_monitoring',
            field=models.ManyToManyField(to='opshub.outilmonitoring'),
        ),
    ]
