# Generated by Django 6.0.7 on 2026-07-23 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opshub', '0003_remove_service_outil_team_service_outils_monitoring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outilmonitoring',
            name='statut',
        ),
        migrations.AlterField(
            model_name='motsclesassignation',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='opshub.equipe'),
        ),
        migrations.AlterField(
            model_name='service',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
