# Generated by Django 6.0.7 on 2026-07-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opshub', '0004_remove_outilmonitoring_statut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outilmonitoring',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='outilmonitoring',
            name='statut',
            field=models.BooleanField(default=True),
        ),
    ]
