# Generated by Django 6.0.7 on 2026-07-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opshub', '0005_outilmonitoring_nom_outilmonitoring_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='plage',
            field=models.CharField(choices=[('matin', 'Matin'), ('apres_midi', 'Après-midi'), ('nuit', 'Nuit')], max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('date', 'plage')},
        ),
    ]
