# Generated by Django 6.0.7 on 2026-07-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opshub', '0006_alter_shift_plage_alter_shift_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='outils_monitoring',
            field=models.ManyToManyField(related_name='services', to='opshub.outilmonitoring'),
        ),
    ]
