# Generated by Django 6.0.7 on 2026-07-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opshub', '0007_alter_service_nom_alter_service_outils_monitoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateurs',
            name='langue',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=5),
        ),
    ]
