# Generated by Django 6.0.7 on 2026-07-28 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opshub', '0008_utilisateurs_langue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateurs',
            name='langue',
        ),
    ]
