# Generated by Django 6.0.7 on 2026-08-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opshub', '0009_remove_utilisateurs_langue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=50, unique=True, verbose_name='ID')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('requester', models.CharField(max_length=150, verbose_name='Requester')),
                ('details', models.TextField(verbose_name='Details')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Feedback')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
        ),
    ]
