# Generated by Django 6.0.7 on 2026-07-31 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opshub', '0009_remove_utilisateurs_langue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outilmonitoring',
            name='lien_acces',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
