# Generated by Django 6.0.7 on 2026-08-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opshub', '0010_alter_outilmonitoring_lien_acces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outilmonitoring',
            name='lien_acces',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='outilmonitoring',
            name='nom',
            field=models.CharField(default='sans nom', max_length=100),
            preserve_default=False,
        ),
    ]
