# Generated by Django 6.1 on 2026-08-11 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opshub', '0010_ticket'),
        ('opshub', '0011_alter_outilmonitoring_lien_acces_and_more'),
    ]

    operations = [
    ]
