# Generated by Django 6.0.7 on 2026-08-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opshub', '0013_permission_role_utilisateurs_role_rolepermission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='code',
            field=models.CharField(choices=[('gerer_outils', 'Créer, modifier, supprimer un outil de monitoring'), ('consulter_outils', 'Consulter le catalogue des outils'), ('gerer_services', 'Créer, modifier, supprimer un service'), ('consulter_services', 'Consulter la liste des services'), ('gerer_mots_cles', 'Créer, modifier, supprimer un mot-clé et son équipe'), ('consulter_mots_cles', "Consulter les mots-clés d'assignation"), ('gerer_utilisateurs', 'Créer, modifier, supprimer un utilisateur'), ('gerer_roles', 'Créer/modifier les rôles et leurs permissions'), ('soumettre_feedback', 'Soumettre un feedback/plainte/recommandation'), ('consulter_feedback', 'Consulter les feedbacks/plaintes/recommandations'), ('supprimer_feedback_tous', "Supprimer n'importe quelle contribution"), ('supprimer_feedback_propre', 'Supprimer ses propres contributions')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='nom',
            field=models.CharField(choices=[('administrateur', 'Administrateur'), ('teamlead', 'Team-lead'), ('membre_techcommand', 'Membre Techcommand')], max_length=50, unique=True),
        ),
    ]
