# Generated by Django 6.0.7 on 2026-08-13 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opshub', '0014_alter_permission_code_alter_role_nom'),
    ]

    operations = [
        # 1. Rediriger d'abord les clés étrangères des feedbacks/plaintes vers Utilisateurs
        migrations.AlterField(
            model_name='recommandation',
            name='membre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='membre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plainte',
            name='membre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),

        # 2. Supprimer les anciens modèles sous-classes
        migrations.DeleteModel(
            name='Administrateur',
        ),
        migrations.DeleteModel(
            name='MembreTechcommand',
        ),
        migrations.DeleteModel(
            name='TeamLead',
        ),

        # 3. Ajouter maintenant le champ 'statut' sur Utilisateurs (sans conflit de nom !)
        migrations.AddField(
            model_name='utilisateurs',
            name='statut',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='utilisateurs',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='opshub.role'),
        ),
    ]