# Generated by Django 6.0.7 on 2026-08-14 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opshub', '0016_alter_permission_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(max_length=50, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ImportLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='import_lot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='opshub.importlot'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('import_lot', 'ticket_id')},
        ),
    ]
