# Generated by Django 6.1 on 2026-08-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opshub', '0017_alter_ticket_ticket_id_importlot_ticket_import_lot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateurs',
            name='theme_sombre',
            field=models.BooleanField(default=False),
        ),
    ]
