# Generated by Django 6.0.7 on 2026-08-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opshub', '0017_alter_ticket_ticket_id_importlot_ticket_import_lot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='nom',
            field=models.CharField(choices=[('administrateur', 'Administrateur'), ('teamlead', 'Team-lead'), ('membre_techcommand', 'Membre Techcommand'), ('senior_manager', 'Senior Manager'), ('manager', 'Manager')], max_length=50, unique=True),
        ),
    ]
