# Generated by Django 6.0.7 on 2026-08-18 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opshub', '0019_alter_permission_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportIncidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports_incidents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(max_length=100, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Issue Description')),
                ('date_signalement', models.DateTimeField(blank=True, null=True, verbose_name='Reported Date')),
                ('severite', models.CharField(blank=True, max_length=10, verbose_name='Severity')),
                ('impact', models.TextField(blank=True, verbose_name='Impact')),
                ('owner_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email du owner')),
                ('rca_fichier', models.FileField(blank=True, null=True, upload_to='rca/', verbose_name='RCA (PDF)')),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En cours'), ('resolu', 'Résolu'), ('ferme', 'Fermé')], default='ouvert', max_length=20)),
                ('dernier_rappel_envoye', models.DateTimeField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('import_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='opshub.importincidents')),
            ],
            options={
                'unique_together': {('import_lot', 'incident_id')},
            },
        ),
    ]
