# Generated by Django 6.0.7 on 2026-08-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opshub', '0020_importincidents_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='action_resolution',
            field=models.TextField(blank=True, verbose_name='Action for Resolution'),
        ),
        migrations.AddField(
            model_name='incident',
            name='affected_service',
            field=models.TextField(blank=True, verbose_name='Affected Service'),
        ),
        migrations.AddField(
            model_name='incident',
            name='duree',
            field=models.DurationField(blank=True, null=True, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='incident',
            name='root_cause',
            field=models.TextField(blank=True, verbose_name='Root Cause'),
        ),
        migrations.AddField(
            model_name='incident',
            name='statut_rca',
            field=models.CharField(blank=True, choices=[('provided', 'Provided'), ('not_provided', 'Not Provided')], max_length=20, verbose_name='RCA Status'),
        ),
    ]
