# Generated by Django 6.0.7 on 2026-08-18 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opshub', '0021_incident_action_resolution_incident_affected_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='statut',
        ),
    ]
