# Generated by Django 6.0.7 on 2026-08-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opshub', '0018_utilisateurs_theme_sombre'),
        ('opshub', '0022_remove_incident_statut'),
    ]

    operations = [
    ]
