# Generated by Django 6.0.7 on 2026-08-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opshub', '0023_merge_20260818_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=150, verbose_name='Assigned to'),
        ),
    ]
