# Generated by Django 6.0.7 on 2026-08-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opshub', '0024_ticket_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='close_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Close date'),
        ),
        migrations.AddField(
            model_name='incident',
            name='in_charge',
            field=models.CharField(blank=True, max_length=150, verbose_name='In charge'),
        ),
        migrations.AddField(
            model_name='incident',
            name='service_now_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='STATUS'),
        ),
        migrations.AddField(
            model_name='incident',
            name='team',
            field=models.CharField(blank=True, max_length=150, verbose_name='TEAM'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='severite',
            field=models.CharField(blank=True, max_length=20, verbose_name='Severity'),
        ),
    ]
