# Generated by Django 6.0.7 on 2026-08-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opshub', '0025_incident_close_date_incident_in_charge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='duree',
        ),
        migrations.AddField(
            model_name='incident',
            name='duree_secondes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duration (secondes)'),
        ),
    ]
