# Generated by Django 6.0.7 on 2026-08-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opshub', '0026_remove_incident_duree_incident_duree_secondes'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='cc_emails',
            field=models.TextField(blank=True, null=True, verbose_name='CC (emails séparés par des virgules)'),
        ),
    ]
