# Generated by Django 6.0.7 on 2026-08-31 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opshub', '0027_incident_cc_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationRappels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequence_jours', models.PositiveIntegerField(default=2, verbose_name='Fréquence des rappels (jours)')),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration des rappels',
                'verbose_name_plural': 'Configuration des rappels',
            },
        ),
        migrations.AlterField(
            model_name='incident',
            name='statut_rca',
            field=models.CharField(blank=True, choices=[('provided', 'Provided'), ('not_provided', 'Not Provided'), ('en_attente', 'En attente')], max_length=20, verbose_name='RCA Status'),
        ),
    ]
