# Generated by Django 6.0.7 on 2026-08-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opshub', '0028_configurationrappels_alter_incident_statut_rca'),
    ]

    operations = [
        migrations.AddField(
            model_name='outilteam',
            name='mail_manager',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='outilteam',
            name='mail_point_de_contact',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
