from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    
    path('outils/', views.liste_outils, name='liste_outils'),
    path('outils/<int:outil_id>/', views.detail_outil, name='detail_outil'),
    path('outils/ajouter/', views.ajouter_outil, name='ajouter_outil'),
    path('outils/<int:outil_id>/modifier/', views.modifier_outil, name='modifier_outil'),
    path('outils/<int:outil_id>/supprimer/', views.supprimer_outil, name='supprimer_outil'),
    path('services/', views.liste_services, name='liste_services'),
    path('services/<int:service_id>/', views.detail_service, name='detail_service'),
    path('services/ajouter/', views.ajouter_service, name='ajouter_service'),
    path('services/<int:service_id>/modifier/', views.modifier_service, name='modifier_service'),
    path('services/<int:service_id>/supprimer/', views.supprimer_service, name='supprimer_service'),
    path('mots-cles/', views.liste_mots_cles, name='liste_mots_cles'),
    path('mots-cles/ajouter/', views.ajouter_mot_cle, name='ajouter_mot_cle'),
    path('mots-cles/<int:mot_cle_id>/modifier/', views.modifier_mot_cle, name='modifier_mot_cle'),
    path('mots-cles/<int:mot_cle_id>/supprimer/', views.supprimer_mot_cle, name='supprimer_mot_cle'),
    path('utilisateurs/', views.liste_utilisateurs, name='liste_utilisateurs'),
    path('utilisateurs/ajouter/', views.ajouter_utilisateur, name='ajouter_utilisateur'),
    path('utilisateurs/<int:user_id>/toggle-statut/', views.toggle_statut_utilisateur, name='toggle_statut_utilisateur'),
    path('utilisateurs/<int:user_id>/supprimer/', views.supprimer_utilisateur, name='supprimer_utilisateur'),
    path('experiences/', views.experiences_membres, name='experiences_membres'),
    path('experiences/feedback/ajouter/', views.ajouter_feedback, name='ajouter_feedback'),
    path('experiences/recommandation/ajouter/', views.ajouter_recommandation, name='ajouter_recommandation'),
    path('experiences/plainte/ajouter/', views.ajouter_plainte, name='ajouter_plainte'),
    path('experiences/feedback/<int:feedback_id>/supprimer/', views.supprimer_feedback, name='supprimer_feedback'),
    path('experiences/recommandation/<int:recommandation_id>/supprimer/', views.supprimer_recommandation, name='supprimer_recommandation'),
    path('experiences/plainte/<int:plainte_id>/supprimer/', views.supprimer_plainte, name='supprimer_plainte'),
    #path('connexion/', views.connexion, name='connexion'),#
    path('index/', views.index, name='index'),
    path('experiences/', views.experiences_membres, name='experiences_membres'),
    path('experiences/feedback/', views.liste_feedbacks, name='liste_feedbacks'),
    path('experiences/plainte/', views.liste_plaintes, name='liste_plaintes'),
    path('experiences/recommandation/', views.liste_recommandations, name='liste_recommandations'),
    path('ajouter-equipe/', views.ajouter_outil_team, name='ajouter_outil_team'),
    path('equipes/ajouter/', views.ajouter_equipe, name='ajouter_equipe'),
    path('outils-team/<int:team_id>/', views.detail_outil_team, name='detail_outil_team'),
    path('parametres/', views.parametres, name='parametres'),
    path('parametres/mot-de-passe/', auth_views.PasswordChangeView.as_view(template_name='changer-mot-de-passe.html', success_url='/parametres/mot-de-passe/succes/'), name='password_change'),
    path('parametres/mot-de-passe/succes/', auth_views.PasswordChangeDoneView.as_view(template_name='mot-de-passe-change.html'), name='password_change_done'),
    path("tickets/", views.page_tickets, name="page_tickets"),
    path("api/imports/", views.liste_imports, name="liste_imports"),
    path("api/imports/import/", views.import_tickets_excel, name="import_tickets_excel"),
    path("api/imports/<int:lot_id>/tickets/", views.tickets_du_lot, name="tickets_du_lot"),
    path("api/imports/<int:lot_id>/export/", views.exporter_lot_excel, name="exporter_lot_excel"),
    path("api/tickets/<int:ticket_pk>/", views.ticket_detail, name="ticket_detail"),
    path("api/imports/<int:lot_id>/", views.supprimer_lot, name="supprimer_lot"),
]